
/*
--Create Customers Table

CREATE TABLE customer (
    customer_id NUMBER PRIMARY KEY, 
    customer_name VARCHAR2(100),
    phone_number VARCHAR2(15),
    city VARCHAR2(50)
);

--Create Accounts Table

CREATE TABLE accounts (
    account_id NUMBER PRIMARY KEY,
    customer_id NUMBER,
    account_type VARCHAR2(20),
    balance NUMBER(12,2),
    account_status VARCHAR2(20),
    created_date DATE,
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

--Create transaction Table
CREATE TABLE transaction (
    txn_id NUMBER PRIMARY KEY,
    from_account NUMBER,
    to_account NUMBER,
    txn_type VARCHAR2(20),
    amount NUMBER(12,2),
    txn_date DATE,
    txn_status VARCHAR2(20)
);

--Create Audit Table
CREATE TABLE account_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_id NUMBER,
    action_type VARCHAR2(50),
    action_date DATE,
    old_balance NUMBER(12,2),
    new_balance NUMBER(12,2)
);

--inserting sample data 

INSERT INTO customer VALUES (1, 'Arjun Kumar', '9876543210', 'Gopalganj');
INSERT INTO customer VALUES (2, 'Rahul Kumar', '9876500000', 'Patna');

INSERT INTO accounts VALUES (1001,1,'SAVINGS',50000,'ACTIVE',SYSDATE);
INSERT INTO accounts VALUES (1002, 2,'SAVINGS',30000,'ACTIVE',SYSDATE);
COMMIT;

--Trigger for checking Negative Balance

CREATE OR REPLACE TRIGGER trg_balance_validation
BEFORE UPDATE OF balance
ON accounts
FOR EACH ROW
BEGIN
    IF :NEW.balance < 0 THEN
        RAISE_APPLICATION_ERROR(-20001,'Insufficient Balance');
    END IF;
END;


--Trigger for Audit Logging
CREATE OR REPLACE TRIGGER trg_account_audit
AFTER UPDATE OF balance
ON accounts
FOR EACH ROW
BEGIN
    INSERT INTO account_audit (account_id,action_type,action_date,old_balance,new_balance)
    VALUES (:NEW.account_id,'BALANCE_UPDATED',SYSDATE,:OLD.balance,:NEW.balance);
END;

--Function to Check Balance

CREATE OR REPLACE FUNCTION get_balance (
    p_account_id NUMBER
)
RETURN NUMBER
IS
    v_balance NUMBER;
BEGIN
    SELECT balance INTO v_balance FROM accounts WHERE account_id = p_account_id;
RETURN v_balance;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;



--Package Specification
CREATE OR REPLACE PACKAGE bank_package
IS
    PROCEDURE deposit_money (p_account_id NUMBER,p_amount NUMBER);
    PROCEDURE withdraw_money (p_account_id NUMBER,p_amount NUMBER );
    PROCEDURE transfer_funds ( p_from_account NUMBER,p_to_account NUMBER,p_amount NUMBER);
    PROCEDURE show_transaction_history (p_account_id NUMBER);
END bank_package;


--Package Body
CREATE OR REPLACE PACKAGE BODY bank_package
IS
    ---------------------------------------------------
    -- Deposit Money
    ---------------------------------------------------

    PROCEDURE deposit_money (
        p_account_id NUMBER,
        p_amount NUMBER
    )
    IS
    BEGIN

        UPDATE accounts SET balance = balance + p_amount WHERE account_id = p_account_id AND account_status = 'ACTIVE';
        INSERT INTO transaction VALUES (transaction_seq.NEXTVAL,NULL,p_account_id,'DEPOSIT',p_amount,SYSDATE,'SUCCESS');
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Amount Deposited Successfully');
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END deposit_money;

    ---------------------------------------------------
    -- Withdraw Money
    ---------------------------------------------------

    PROCEDURE withdraw_money (
        p_account_id NUMBER,
        p_amount NUMBER
    )
    IS
        v_balance NUMBER;
    BEGIN
        SELECT balance INTO v_balance FROM accounts WHERE account_id = p_account_id AND account_status = 'ACTIVE';
        IF p_amount > 20000 THEN
            RAISE_APPLICATION_ERROR(-20002,'Daily ATM Withdrawal Limit Exceeded');
        END IF;
        IF v_balance < p_amount THEN
            RAISE_APPLICATION_ERROR(-20003,'Insufficient Funds');
        END IF;

        UPDATE accounts SET balance = balance - p_amount WHERE account_id = p_account_id;

        INSERT INTO transaction VALUES (transaction_seq.NEXTVAL,p_account_id,NULL,'WITHDRAW',p_amount,SYSDATE,'SUCCESS');
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Withdrawal Successful');

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END withdraw_money;

    ---------------------------------------------------
    -- Fund Transfer
    ---------------------------------------------------

    PROCEDURE transfer_funds (
        p_from_account NUMBER,
        p_to_account NUMBER,
        p_amount NUMBER
    )
    IS
        v_balance NUMBER;
    BEGIN

        SELECT balance INTO v_balance FROM accounts WHERE account_id = p_from_account AND account_status = 'ACTIVE';

        IF v_balance < p_amount THEN
            RAISE_APPLICATION_ERROR(-20004,'Insufficient Balance For Transfer');
        END IF;

        UPDATE accounts SET balance = balance - p_amount WHERE account_id = p_from_account;

        UPDATE accounts SET balance = balance + p_amount WHERE account_id = p_to_account;

        INSERT INTO transaction
        VALUES (transaction_seq.NEXTVAL,p_from_account,p_to_account,'TRANSFER',p_amount,SYSDATE,'SUCCESS');
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Fund Transfer Successful');

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            INSERT INTO transaction
            VALUES (transaction_seq.NEXTVAL,p_from_account,p_to_account,'TRANSFER',p_amount,SYSDATE,'FAILED');
            DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END transfer_funds;

    ---------------------------------------------------
    -- Transaction History Using Cursor
    ---------------------------------------------------
    PROCEDURE show_transaction_history (
        p_account_id NUMBER
    )
    IS
        CURSOR c_txn IS SELECT txn_id,txn_type,amount,txn_date,txn_status
        FROM transaction 
        WHERE from_account = p_account_id OR to_account = p_account_id 
        ORDER BY txn_date DESC;
        v_txn_id transaction.txn_id%TYPE;
        v_type transaction.txn_type%TYPE;
        v_amount transaction.amount%TYPE;
        v_date transaction.txn_date%TYPE;
        v_status transaction.txn_status%TYPE;
    BEGIN
        OPEN c_txn;
        LOOP
            FETCH c_txn INTO v_txn_id,v_type,v_amount,v_date,v_status;
            EXIT WHEN c_txn%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Txn ID : ' || v_txn_id ||' | Type : ' || v_type ||' | Amount : ' || v_amount || ' | Status : ' || v_status);
        END LOOP;
        CLOSE c_txn;
    END show_transaction_history;
END bank_package;


---Create Sequence
CREATE SEQUENCE transaction_seq START WITH 1 INCREMENT BY 1;

--reate Indexes for Better Performance
CREATE INDEX idx_account_customer ON accounts(customer_id);
CREATE INDEX idx_transaction_account ON transaction(from_account, to_account);


----------------DEMO------------------
select * from accounts;
select * from transaction;
select * from customer;

--for deposite give (account_no,amount) 
BEGIN
    bank_package.deposit_money(1001,5000);
END;

--for withdraw give (account_no,amount)
BEGIN
    bank_package.withdraw_money(1001,3000);
END;
--transafer money from one account to another 
--(from account,to account,amount)
BEGIN
    bank_package.transfer_funds(1001,1002,7000);
END;
--see transaction history for an account
BEGIN
    bank_package.show_transaction_history(1001);
END;
--check Balance 
BEGIN
    dbms_output.put_line(get_balance(1001));
END;

